import type { SupportedIndustry } from "@/lib/industries";

import type { BudgetConfig } from "./types";

/**
 * Sensible starter budgets per industry. The freelancer can edit
 * everything afterwards from /edit; these are just "don't start at zero"
 * defaults so the public /[handle]/budget page is useful on day one.
 */
export const BUDGET_TEMPLATES: Record<SupportedIndustry, BudgetConfig> = {
  "graphic-designer": {
    enabled: false,
    introText:
      "Dime qué necesitas y te doy una estimación orientativa al momento. Si tiene sentido, seguimos hablando.",
    suggestBooking: true,
    items: [
      {
        id: "identity",
        name: "Identidad de marca",
        description: "Logo, sistema visual y guía de uso. 2-3 semanas.",
        basePrice: 1200,
        unit: "project",
        selectable: true,
        defaultSelected: true,
        options: [
          { id: "essentials", label: "Essentials", multiplier: 1 },
          { id: "full-system", label: "Sistema completo + plantillas", multiplier: 1.6 },
        ],
      },
      {
        id: "web-design",
        name: "Diseño web (Figma)",
        description: "Landing o site multi-página listo para maquetar.",
        basePrice: 900,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [
          { id: "landing", label: "Landing (1 página)", multiplier: 1 },
          { id: "site-3-5", label: "Site 3-5 páginas", multiplier: 1.8 },
          { id: "site-6-10", label: "Site 6-10 páginas", multiplier: 2.6 },
        ],
      },
      {
        id: "socials",
        name: "Pack redes sociales",
        description: "Plantillas editables + 10 piezas iniciales.",
        basePrice: 350,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
    ],
  },
  developer: {
    enabled: false,
    introText: "Cuéntame el proyecto en 2-3 frases y te mando una estimación.",
    suggestBooking: true,
    items: [
      {
        id: "landing",
        name: "Landing de producto",
        description: "Diseño + dev + analytics en 1-2 semanas.",
        basePrice: 1500,
        unit: "project",
        selectable: true,
        defaultSelected: true,
        options: [
          { id: "standard", label: "Estándar", multiplier: 1 },
          { id: "animated", label: "Con animaciones y motion", multiplier: 1.35 },
        ],
      },
      {
        id: "webapp",
        name: "App web a medida",
        description: "Stack moderno, tests, deploy. Sprints de 2 semanas.",
        basePrice: 4500,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [
          { id: "mvp", label: "MVP (2-3 semanas)", multiplier: 1 },
          { id: "extended", label: "Producto extendido (6-8 semanas)", multiplier: 2.8 },
        ],
      },
      {
        id: "consulting",
        name: "Consultoría técnica",
        description: "Revisión de arquitectura y code review.",
        basePrice: 85,
        unit: "hour",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
    ],
  },
  "ux-designer": {
    enabled: false,
    introText: "Dame contexto del producto y te propongo alcance + precio.",
    suggestBooking: true,
    items: [
      {
        id: "audit",
        name: "Auditoría UX",
        description: "Revisión de producto existente con plan priorizado.",
        basePrice: 900,
        unit: "project",
        selectable: true,
        defaultSelected: true,
        options: [],
      },
      {
        id: "product-design",
        name: "Diseño de producto completo",
        description: "Research + flujos + UI. Proyectos 4-8 semanas.",
        basePrice: 3500,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [
          { id: "compact", label: "Compacto (4 sem.)", multiplier: 1 },
          { id: "full", label: "Completo (8 sem.)", multiplier: 1.9 },
        ],
      },
      {
        id: "design-system",
        name: "Design system",
        description: "Tokens, componentes y documentación en Figma.",
        basePrice: 2500,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
    ],
  },
  photographer: {
    enabled: false,
    introText: "Dime tipo de sesión, fecha y ubicación — te respondo con disponibilidad y precio.",
    suggestBooking: false,
    items: [
      {
        id: "portrait",
        name: "Sesión de retrato",
        description: "1-2h, 15-20 fotos retocadas en 5 días.",
        basePrice: 280,
        unit: "project",
        selectable: true,
        defaultSelected: true,
        options: [],
      },
      {
        id: "brand-content",
        name: "Contenido para marcas",
        description: "Media jornada, ~40 fotos seleccionadas.",
        basePrice: 650,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [
          { id: "half-day", label: "Media jornada", multiplier: 1 },
          { id: "full-day", label: "Jornada completa", multiplier: 1.7 },
        ],
      },
      {
        id: "event",
        name: "Cobertura de evento",
        description: "Jornada completa, galería online privada.",
        basePrice: 900,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
    ],
  },
  copywriter: {
    enabled: false,
    introText: "Cuéntame el proyecto y te paso una estimación.",
    suggestBooking: false,
    items: [
      {
        id: "landing-copy",
        name: "Copy de landing",
        description: "Brief + 2 rondas de revisión. 1 semana.",
        basePrice: 650,
        unit: "project",
        selectable: true,
        defaultSelected: true,
        options: [],
      },
      {
        id: "email-sequence",
        name: "Secuencia de email",
        description: "Welcome flow o campaña de lanzamiento.",
        basePrice: 450,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [
          { id: "3-emails", label: "3 emails", multiplier: 1 },
          { id: "7-emails", label: "7 emails", multiplier: 2.1 },
        ],
      },
      {
        id: "article",
        name: "Artículo SEO",
        description: "1500-2500 palabras con keyword research.",
        basePrice: 250,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
    ],
  },
  coach: {
    enabled: false,
    introText:
      "Primera sesión gratuita de descubrimiento. Si seguimos, estos son los formatos habituales.",
    suggestBooking: true,
    items: [
      {
        id: "individual",
        name: "Sesión individual",
        description: "60 min online.",
        basePrice: 95,
        unit: "hour",
        selectable: true,
        defaultSelected: true,
        options: [],
      },
      {
        id: "program",
        name: "Programa 3 meses",
        description: "Sesiones quincenales + plan de desarrollo.",
        basePrice: 850,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
      {
        id: "team",
        name: "Facilitación de equipo",
        description: "Workshops 2-4h sobre comunicación y visión.",
        basePrice: 650,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
    ],
  },
  "marketing-consultant": {
    enabled: false,
    introText: "Dime en qué punto está el producto y qué canales te interesan.",
    suggestBooking: true,
    items: [
      {
        id: "audit",
        name: "Auditoría de marketing",
        description: "Análisis completo + roadmap priorizado.",
        basePrice: 1200,
        unit: "project",
        selectable: true,
        defaultSelected: true,
        options: [],
      },
      {
        id: "monthly",
        name: "Gestión mensual",
        description: "Ejecución, reportes y optimización continua.",
        basePrice: 1800,
        unit: "month",
        selectable: true,
        defaultSelected: false,
        options: [
          { id: "part-time", label: "Parcial (10h/sem)", multiplier: 1 },
          { id: "full", label: "Full (20h/sem)", multiplier: 1.8 },
        ],
      },
      {
        id: "strategy",
        name: "Consultoría estratégica",
        description: "Sesiones con founder o dirección.",
        basePrice: 150,
        unit: "hour",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
    ],
  },
  architect: {
    enabled: false,
    introText: "Dime metros, ubicación y tipo de proyecto para darte una estimación.",
    suggestBooking: true,
    items: [
      {
        id: "project-basic",
        name: "Proyecto básico + ejecución",
        description: "Con memoria, planos y mediciones.",
        basePrice: 3500,
        unit: "project",
        selectable: true,
        defaultSelected: true,
        options: [],
      },
      {
        id: "site-direction",
        name: "Dirección de obra",
        description: "Visitas semanales y certificaciones.",
        basePrice: 1200,
        unit: "month",
        selectable: true,
        defaultSelected: false,
        options: [],
      },
      {
        id: "turnkey",
        name: "Reforma integral llave en mano",
        description: "De diseño a entrega.",
        basePrice: 950,
        unit: "project",
        selectable: true,
        defaultSelected: false,
        options: [
          { id: "50-80m", label: "50-80 m²", multiplier: 50 },
          { id: "80-150m", label: "80-150 m²", multiplier: 110 },
          { id: "150plus", label: "+150 m²", multiplier: 180 },
        ],
      },
    ],
  },
};

export function getBudgetTemplate(industry: SupportedIndustry): BudgetConfig {
  return BUDGET_TEMPLATES[industry];
}
